baseURL = "https://amayuelas.github.io/my-website/"
languageCode = "en-us"
title = "Alfonso Amayuelas"
paginate = 10

[params]
description = "PhD student @ UC Santa Barbara"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "https://amayuelas.github.io/my-website/"
    weight = 1
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "https://amayuelas.github.io/my-website/experience/"
    weight = 2
  [[menu.main]]
    identifier = "education"
    name = "Education"
    url = "https://amayuelas.github.io/my-website/education/"
    weight = 3
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "https://amayuelas.github.io/my-website/publications/"
    weight = 4
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "https://amayuelas.github.io/my-website/blog/"
    weight = 5
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "https://amayuelas.github.io/my-website/files/CV.pdf"
    weight = 6